//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::author::Entity as Author;
pub use super::post::Entity as Post;
pub use super::tag::Entity as Tag;
pub use super::tag_relation::Entity as TagRelation;
pub use super::test_model::Entity as TestModel;
